schedules:
# - cron: "*/15 * * * *"
  branches:
    include: [ main ]
  always: true


jobs:
  - job: sample_nuget_test
    pool:
      vmImage: macos-10.15
    steps:
    - script: env
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
    - pwsh: dotnet build
    - pwsh: dotnet test --no-build --verbosity normal
